./search_mode.sh s01
./search_mode.sh s02
./search_mode.sh s03
./search_mode.sh s04
./search_mode.sh s05
./search_mode.sh s06
./search_mode.sh s07
./search_mode.sh s08
./search_mode.sh s09
./search_mode.sh s10
./search_mode.sh s11
./search_mode.sh s12
./search_mode.sh s13
./search_mode.sh s14
./search_mode.sh s15
./search_mode.sh s16
./search_mode.sh s17
./search_mode.sh s18
