ssh -i ~/.ssh/meerkat.pem s01 "service elasticsearch start"
echo "Waiting 60 seconds."
sleep 60
ssh -i ~/.ssh/meerkat.pem s02 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s03 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s04 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s05 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s06 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s07 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s08 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s09 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s10 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s11 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s12 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s13 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s14 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s15 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s16 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s17 "service elasticsearch start"
ssh -i ~/.ssh/meerkat.pem s18 "service elasticsearch start"

