#!/bin/bash

# chkconfig: 345 99 10
# description: This script should run during system startup on ES nodes
# 
# remember to use chkconfig --add file_daemon as root when installing
#

RETVAL=0
prog="(source /etc/bashrc; cd /root/git/Meerkat; nohup /usr/local/bin/python3.3 -m meerkat.file_daemon > /var/log/file_daemon.log 2>&1 &)"
exec="file_daemon"
lockfile=/var/lock/subsys/file_daemon

# Get functions from functions library
. /etc/rc.d/init.d/functions

[ $UID -eq 0 ]

# Start the file_daemon

start() {
	if [ $UID -ne 0 ] ; then
		echo "User has insufficient privilege."
		exit 4
	fi
	echo -n $"Starting $prog: "
	daemon $prog
	retval=$?
	echo
	[ $retval -eq 0 ] && touch $lockfile
}
# Stop the file_daemon
stop() {
	if [ $UID -ne 0 ] ; then
		echo "User has insufficient privilege."
		exit 4
	fi
	echo -n $"Stopping $prog: "
	if [ -n "`pidfileofproc $exec`" ]; then
		killproc $exec
		RETVAL=3
	else
		failure $"Stopping $prog"
	fi
	retval=$?
	echo
	[ $retval -eq 0 ] && rm -f $lockfile
}
### main logic ###
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status file_daemon
		;;
	restart|reload|condrestart)
		stop
		start
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|status}"
		exit 1
esac
exit 0
