#!/bin/bash

# chkconfig: 345 99 10
# description: This script should run during system startup on ES nodes
# 
# remember to use chkconfig --add mount_data_commands as root when installing
#
case "$1" in
	'start')
		mkdir -p /data/0
		mkdir -p /data/1
		mkdir -p /data/2
		mount /dev/xvdb /data/0
		mount /dev/xvdc /data/1
		mount /dev/xvdf /data/2
		mkdir -p /data/0/input
		mkdir -p /data/0/output
		mkdir -p /data/1/input
		mkdir -p /data/1/output
		mkdir -p /data/1/error
		mkdir -p /data/2/input
		mkdir -p /data/2/output
		mkdir -p /data/1/log/elasticsearch
		chown -R elasticsearch /data
		;;
	'stop')
		pkill elasticsearch
		;;
esac

